export {default as Home} from './Home'
export {default as Navbar } from './Navbar'
export {default as Footer } from './Footer'
export {default as About} from './About'
export {default as Info} from './Info'
