export {default as Home} from './Home'
export {default as Navbar } from './Navbar'
export {default as Footer } from './Footer'
export {default as Info} from './Info'
export {default as SinglePage} from './SinglePage'
export {default as Holdings} from './Holdings'
export {default as LandingCarousel} from './LandingCarousel'
export {default as Services} from './Services'
